Feature 1
DianaBeki/Hello-microverse pull request #1
Opened 2022-10-25 18:29 UTC by DianaBeki

### Feature

In this feature:

Added an index.html file 
Added a style.css 
Added a .gitignore file

2022-10-25 18:55 UTC, ichala requested changes
Hi @DianaBeki  
Good job so far! 
👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Good Pr Description✔️ 
- Meaningful commits ✔️
- Linters are working ✔️

_**Notes To Consider For Your Next Projects**_

- Good Job so far, your commit message is clear and meaningful but kindly make sure in your next projects, The commit message should be written in the imperative tense and capitalized example: Add styling to the header, Add .gitignore file, etc ...
- Your branch name should be a name of a feature and not literally named `feature`, it should be a bit descriptive and meaningful example: `setup-project`, since changing the name of the branch will cause some issues and one of them is closing opened PR, kindly make sure to implement that in your future projects


 ## Required Changes ♻️


- [ ] 🛑 Pull Request should have a descriptive title telling you what changes are inside. kindly update your PR title to something more descriptive, like ; ' Setup Hello Project'
- [x] 🛑 in your readme file currently your license link is broken, kindly try to fix it




## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 20:46 UTC, vickymarz requested changes
Hi @DianaBeki, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 20:46 UTC, vickymarz commented on README.md
> +This project is MIT licensed.
- [ ] As the previous reviewer suggested, the link to your MIT license is broken because the file is absent in your project directory. Kindly add the MIT.md file and add the link in your readme 👍🏽

2022-10-26 06:37 UTC, DianaBeki commented on README.md
> +This project is MIT licensed.
Done

2022-10-26 06:38 UTC, DianaBeki commented
Fixed link to MIT license on README.md file

2022-10-26 06:44 UTC, topeogunleye approved these changes
### Hi @DianaBeki, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
- [ ]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
<img width="265" alt="image" src="https://user-images.githubusercontent.com/52934128/197953625-22787fb1-607f-4975-a70c-f5bfd16fd97b.png"> 

### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 07:38 UTC, merged